#!/usr/bin/env python3
"""Сборка Java-агента: компиляция agent/src/**/*.java (JDK 8) →
protected-кодирование каждого .class → генерация jni/dll/src/agent_payload.h.

Таблица AgentClassBlob в хедере содержит ВСЕ классы (включая внутренние/лямбды).
Каждый блоб проверяется round-trip'ом: decode(encode(x)) == x, иначе сборка падает.
"""
import argparse
import os
import struct
import subprocess
import sys
import tempfile

TOOLS = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, TOOLS)
sys.path.insert(0, os.path.join(TOOLS, '..'))
import decryptor as D  # noqa: E402
from encode_protected import encode_protected  # noqa: E402

# JDK8-пути по приоритету: наш Program Files (реально установлен) → старый
# AppData-путь (остался от чужой машины/переезда JDK). Первый существующий.
DEFAULT_JAVAC_CANDIDATES = [
    r"C:\Program Files\Eclipse Adoptium\jdk-8.0.502.7-hotspot\bin\javac.exe",
    r"C:\Users\Admin\AppData\Local\Programs\Eclipse Adoptium\jdk-8.0.504.1-hotspot\bin\javac.exe",
]
DEFAULT_JAVAC = next((c for c in DEFAULT_JAVAC_CANDIDATES if os.path.isfile(c)),
                     DEFAULT_JAVAC_CANDIDATES[0])
DEFAULT_ENTRY = "client/RustClient"


def find_javac(explicit):
    if explicit:
        return explicit if os.path.isfile(explicit) else None
    env = os.environ.get("JDK8_JAVAC")
    if env and os.path.isfile(env):
        return env
    return DEFAULT_JAVAC if os.path.isfile(DEFAULT_JAVAC) else None


# Шрифты, вшиваемые в payload (FontData.java). Диск остаётся dev-оверрайдом
# в MsdfFont (если файлы есть — читаются они, иначе встроенные байты).
FONTS_TO_EMBED = [
    ("medium", "json"),
    ("medium", "png"),
    ("sf_semibold", "json"),
    ("sf_semibold", "png"),
]
FONT_CHUNK = 60000  # CP UTF8 limit 65535 — чанки с запасом


def generate_font_data(src_dir):
    """ЕСЛИ fonts/msdf существует — регенерирует src/utils/render/FontData.java
    (Base64-чанки) из файлов. Шрифты с диска УДАЛЕНЫ: единственный источник —
    FontData.java в src (едет в payload). Чтобы обновить шрифт — положи файлы
    обратно в fonts/msdf и пересобери."""
    fonts_dir = os.path.normpath(os.path.join(src_dir, "..", "fonts", "msdf"))
    if not os.path.isdir(fonts_dir):
        out_path = os.path.join(src_dir, "utils", "render", "FontData.java")
        if os.path.isfile(out_path):
            print("[pack-fonts] fonts/msdf отсутствует — использую существующий FontData.java")
            return
        raise SystemExit("pack_fonts: нет ни fonts/msdf, ни FontData.java — шрифтам неоткуда взяться")
    parts = []
    total = 0
    for base, ext in FONTS_TO_EMBED:
        path = os.path.join(fonts_dir, "%s.%s" % (base, ext))
        if not os.path.isfile(path):
            raise SystemExit("pack_fonts: missing font file: %s" % path)
        raw = open(path, "rb").read()
        total += len(raw)
        b64 = __import__("base64").b64encode(raw).decode("ascii")
        field = ("%s_%s" % (base.upper(), ext.upper())).replace(".", "_")
        chunks = [b64[i:i + FONT_CHUNK] for i in range(0, len(b64), FONT_CHUNK)]
        arr = "new String[] {\n" + ",\n".join('        "%s"' % c for c in chunks) + "\n    }"
        parts.append("    public static final String[] %s = %s;" % (field, arr))
        print("[pack-fonts] %-22s raw=%7d b64=%7d chunks=%d" % (base + "." + ext, len(raw), len(b64), len(chunks)))
    java = (
        "package utils.render;\n\n"
        "// Auto-generated by tools/pack_agent.py (generate_font_data) — DO NOT EDIT.\n"
        "// Шрифты MSDF, вшитые в DLL-payload (Base64-чанки; CP UTF8 limit 64KB).\n"
        "// MsdfFont читает диск только как dev-оверрайд, иначе отсюда.\n"
        "public final class FontData {\n"
        "    private FontData() {}\n\n"
        + "\n".join(parts) + "\n\n"
        "    /** Декодирует встроенный атлас; null если пара font/ext не вшита. */\n"
        "    public static byte[] get(String fontBase, String ext) {\n"
        "        String[] chunks;\n"
        '        if ("medium".equals(fontBase) && "json".equals(ext)) chunks = MEDIUM_JSON;\n'
        '        else if ("medium".equals(fontBase) && "png".equals(ext)) chunks = MEDIUM_PNG;\n'
        '        else if ("sf_semibold".equals(fontBase) && "json".equals(ext)) chunks = SF_SEMIBOLD_JSON;\n'
        '        else if ("sf_semibold".equals(fontBase) && "png".equals(ext)) chunks = SF_SEMIBOLD_PNG;\n'
        "        else return null;\n"
        "        StringBuilder sb = new StringBuilder();\n"
        "        for (int i = 0; i < chunks.length; i++) sb.append(chunks[i]);\n"
        "        try {\n"
        "            return java.util.Base64.getDecoder().decode(sb.toString());\n"
        "        } catch (Throwable t) {\n"
        "            return null;\n"
        "        }\n"
        "    }\n"
        "}\n"
    )
    out_path = os.path.join(src_dir, "utils", "render", "FontData.java")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    open(out_path, "w", encoding="utf-8").write(java)
    print("[pack-fonts] FontData.java: %d fonts, %d KB raw -> %d KB source (%s)"
          % (len(FONTS_TO_EMBED), total // 1024, len(java) // 1024, out_path))


def collect_sources(src_dir):
    out = []
    for root, _dirs, files in os.walk(src_dir):
        for fn in sorted(files):
            if fn.endswith(".java"):
                out.append(os.path.join(root, fn))
    return out


ASSETS_TO_EMBED = [
    # (имя ассета, относительный путь от src/assets)
    ("putin", "putin.png"),
    ("arrow", "arrow.png"),
]


def generate_asset_data(src_dir):
    """Регенерирует src/utils/etc/AssetData.java из src/assets/*.png
    (Base64-чанки, как FontData). Обновил картинку — просто пересобери."""
    assets_dir = os.path.join(src_dir, "assets")
    if not os.path.isdir(assets_dir):
        raise SystemExit("pack_assets: нет папки %s" % assets_dir)
    parts = []
    total = 0
    for name, rel in ASSETS_TO_EMBED:
        path = os.path.join(assets_dir, rel)
        if not os.path.isfile(path):
            raise SystemExit("pack_assets: missing asset file: %s" % path)
        raw = open(path, "rb").read()
        total += len(raw)
        b64 = __import__("base64").b64encode(raw).decode("ascii")
        field = name.upper().replace(".", "_")
        chunks = [b64[i:i + FONT_CHUNK] for i in range(0, len(b64), FONT_CHUNK)]
        arr = "new String[] {\n" + ",\n".join('        "%s"' % c for c in chunks) + "\n    }"
        parts.append("    public static final String[] %s = %s;" % (field, arr))
        print("[pack-assets] %-16s raw=%7d b64=%7d chunks=%d" % (name, len(raw), len(b64), len(chunks)))
    java = (
        "package utils.etc;\n\n"
        "// Auto-generated by tools/pack_agent.py (generate_asset_data) — DO NOT EDIT.\n"
        "// PNG-ассеты, вшитые в DLL-payload (Base64-чанки; CP UTF8 limit 64KB).\n"
        "public final class AssetData {\n"
        "    private AssetData() {}\n\n"
        + "\n".join(parts) + "\n\n"
        "    /** Декодирует встроенный ассет; null если имя не вшито. */\n"
        "    public static byte[] get(String name) {\n"
        "        String[] chunks;\n"
        '        if ("putin".equals(name)) chunks = PUTIN;\n'
        '        else if ("arrow".equals(name)) chunks = ARROW;\n'
        "        else return null;\n"
        "        StringBuilder sb = new StringBuilder();\n"
        "        for (int i = 0; i < chunks.length; i++) sb.append(chunks[i]);\n"
        "        try {\n"
        "            return java.util.Base64.getDecoder().decode(sb.toString());\n"
        "        } catch (Throwable t) {\n"
        "            return null;\n"
        "        }\n"
        "    }\n"
        "}\n"
    )
    out_path = os.path.join(src_dir, "utils", "etc", "AssetData.java")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    open(out_path, "w", encoding="utf-8").write(java)
    print("[pack-assets] AssetData.java: %d assets, %d KB raw -> %d KB source (%s)"
          % (len(ASSETS_TO_EMBED), total // 1024, len(java) // 1024, out_path))


def compile_sources(javac, src_dir, out_dir, cp=None):
    sources = collect_sources(src_dir)
    if not sources:
        raise SystemExit("pack_agent: no .java sources in %s" % src_dir)
    os.makedirs(out_dir, exist_ok=True)
    cmd = [javac, "-encoding", "UTF-8", "-source", "8", "-target", "8",
           "-d", out_dir]
    if cp:
        cmd += ["-classpath", cp]
    cmd += sources
    print("[pack] javac:", " ".join(cmd[1:3]), "... (%d sources)" % len(sources))
    r = subprocess.run(cmd, capture_output=True, text=True, errors="replace")
    if r.returncode != 0:
        print(r.stdout)
        print(r.stderr)
        raise SystemExit("pack_agent: javac failed")
    if r.stderr.strip():
        for line in r.stderr.strip().splitlines():
            if "warning" not in line.lower():
                print("[pack][javac]", line)


def class_files(out_dir):
    out = []
    for root, _dirs, files in os.walk(out_dir):
        for fn in sorted(files):
            if fn.endswith(".class"):
                out.append(os.path.join(root, fn))
    return sorted(out)


def class_header(data):
    """(this_class, [суперкласс + интерфейсы]) одним проходом CP.
    DefineClass резолвит ЗАГОЛОВОК класса eagerly — если суперкласс/интерфейс
    из payload ещё не определён, define возвращает 0 (баг 09-10: Module$BoolSetting
    extends Module$Setting шёл в payload раньше родителя по алфавиту →
    NoClassDefFoundError). Поэтому payload сортируется топологически."""
    cpc = struct.unpack_from(">H", data, 8)[0]
    q = 10
    utf = {}
    classes = {}
    i = 1
    while i < cpc:
        t = data[q]; q += 1
        if t == 1:
            ln = struct.unpack_from(">H", data, q)[0]; q += 2
            utf[i] = data[q:q+ln].decode('latin1'); q += ln
        elif t in (3, 4):
            q += 4
        elif t in (5, 6):
            q += 8; i += 1
        elif t == 7:
            classes[i] = struct.unpack_from(">H", data, q)[0]; q += 2
        elif t == 8:
            q += 2
        elif t == 16:
            q += 2
        elif t in (9, 10, 11, 12, 17, 18):
            q += 4
        elif t == 15:
            q += 3
        else:
            raise ValueError("bad CP tag %d in class file" % t)
        i += 1

    def cls(idx):
        if not idx:
            return None
        name_idx = classes.get(idx)
        return utf.get(name_idx) if name_idx else None

    this_idx = struct.unpack_from(">H", data, q + 2)[0]
    super_idx = struct.unpack_from(">H", data, q + 4)[0]
    nif = struct.unpack_from(">H", data, q + 6)[0]
    deps = []
    sc = cls(super_idx)
    if sc:
        deps.append(sc)
    for k in range(nif):
        ifc = cls(struct.unpack_from(">H", data, q + 8 + k * 2)[0])
        if ifc:
            deps.append(ifc)
    return cls(this_idx), deps


def topo_sort_classes(infos):
    """infos: [(name, deps, path)]. Порядок define: родители раньше детей
    (Kahn; среди готовых — по алфавиту, детерминизм; циклов в заголовках
    не бывает, на всякий случай остаток отдаётся как есть)."""
    names = [it[0] for it in infos]
    in_set = set(names)
    deps = {it[0]: [d for d in it[1] if d in in_set and d != it[0]] for it in infos}
    order = []
    emitted = set()
    pending = sorted(names)
    while pending:
        ready = [n for n in pending if all(d in emitted for d in deps[n])]
        if not ready:
            order.extend(pending)
            break
        for n in ready:
            order.append(n)
            emitted.add(n)
        pending = [n for n in pending if n not in emitted]
    return order


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default=os.path.join(TOOLS, "..", "jni", "agent", "src"))
    ap.add_argument("--out", default=os.path.join(TOOLS, "..", "jni", "dll", "src"))
    ap.add_argument("--build", default=os.path.join(TOOLS, "..", "jni", "agent", "build"))
    ap.add_argument("--javac", default=None)
    ap.add_argument("--entry", default=DEFAULT_ENTRY, help="slash-имя класса с install()")
    ap.add_argument("--cp", default=None, help="classpath для javac (через ;)")
    args = ap.parse_args()

    src_dir = os.path.abspath(args.src)
    out_header = os.path.abspath(os.path.join(args.out, "agent_payload.h"))
    build_dir = os.path.abspath(args.build)

    javac = find_javac(args.javac)
    if not javac:
        raise SystemExit("pack_agent: javac (JDK 8) not found — set JDK8_JAVAC or --javac")

    # 0) регенерируем FontData.java из fonts/msdf + AssetData.java из src/assets
    generate_font_data(src_dir)
    generate_asset_data(src_dir)

    # 1) компиляция (чистим build, чтобы старые .class не попадали в payload)
    if os.path.isdir(build_dir):
        import shutil
        shutil.rmtree(build_dir)
    compile_sources(javac, src_dir, build_dir, cp=args.cp)

    # 2) заголовки классов → топопорядок (родители до потомков; иначе
    #    DefineClass потомка даёт 0, см. class_header)
    infos = []
    for path in class_files(build_dir):
        data = open(path, "rb").read()
        if not data.startswith(b"\xCA\xFE\xBA\xBE"):
            raise SystemExit("pack_agent: %s is not a class file" % path)
        name, deps = class_header(data)
        infos.append((name, deps, path))
    if not infos:
        raise SystemExit("pack_agent: no classes compiled")
    by_name = {it[0]: it for it in infos}
    order = topo_sort_classes(infos)

    # 3) кодирование в topo-порядке + round-trip проверка
    classes = []
    for name in order:
        path = by_name[name][2]
        data = open(path, "rb").read()
        enc = encode_protected(data)
        if D.decode_protected(enc) != data:
            raise SystemExit("pack_agent: round-trip FAILED for %s" % path)
        classes.append((name, enc))
        print("[pack] %-40s plain=%d enc=%d OK" % (name, len(data), len(enc)))

    entry = args.entry.replace(".", "/")
    if not any(name == entry for name, _ in classes):
        raise SystemExit("pack_agent: entry class %s not found among classes" % entry)

    # 3) генерация agent_payload.h
    lines = []
    lines.append("#pragma once")
    lines.append("// Auto-generated by tools/pack_agent.py — DO NOT EDIT.")
    lines.append("// Источник: jni/agent/src/**/*.java (JDK8, protected-формат, DR0-bypass)")
    for i, (name, enc) in enumerate(classes):
        var = "g_agent_data_%d" % i
        lines.append("static const unsigned int %s_size = %d;" % (var, len(enc)))
        lines.append("static const unsigned char %s[] = {" % var)
        for j in range(0, len(enc), 16):
            lines.append("    " + ",".join("0x%02x" % b for b in enc[j:j+16]) + ",")
        lines.append("};")
    lines.append("#include <cstddef>")
    lines.append("struct AgentClassBlob { const char* name; const unsigned char* data; unsigned int size; };")
    lines.append("static const AgentClassBlob g_agentClasses[] = {")
    for i, (name, enc) in enumerate(classes):
        lines.append('    { "%s", g_agent_data_%d, g_agent_data_%d_size },' % (name, i, i))
    lines.append("};")
    lines.append("static const unsigned int g_agentClassCount = sizeof(g_agentClasses) / sizeof(g_agentClasses[0]);")
    lines.append('static const char* const g_agentEntryName = "%s";' % entry)

    os.makedirs(os.path.dirname(out_header), exist_ok=True)
    open(out_header, "w").write("\n".join(lines) + "\n")
    print("[pack] %d classes -> %s (entry: %s)" % (len(classes), out_header, entry))


if __name__ == "__main__":
    main()
